using Microsoft.SemanticKernel;
using PdfReader;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using UglyToad.PdfPig.Graphics;


namespace Agent_Ollama.Plugins;

internal class PdfContentPlugin
{

const string PDFPath = @"PDFs/";
const string PDFFileName = @"VN";

// The Kernel is automatically injected into the plugin methods if they require it.
// This allows the plugin to use the kernel's configured AI services.

/// <summary>
/// Read PDF chunks and uses the kernel to summarize them.
/// </summary>
/// <param name="kernel">The Semantic Kernel instance (injected automatically).</param>
/// <param name="filePath">The path to the text file to be summarized.</param>
/// <returns>A summary of the file content generated by the LLM.</returns>
[KernelFunction("SummarizeFile")]
[Description("Reads a text file and generates a summary of its content using an AI model.")]
public async Task<string> SummarizeFile(
    Kernel kernel,
    [Description("The full path to the pdf text file to summarize.")] string pdfFileName 
    )
{
        using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(5));

        try
        {
            string prompt = "";

            if (kernel is not null)
            {
                var builder = Kernel.CreateBuilder();

                //var kernel = builder.Build();

                Reader reader = new Reader();
                var pdftxt = reader.ReadPdf(pdfFileName);

                // Create a prompt for the AI model.Instruct the model to summarize the provided text.
                prompt = @$"Find and create Key-Value list of parts from text provided below. Sample Key-Value pair: 'Washer    DM-2524'
                If the text is too short or doesn't contain meaningful information, state that.

                Text to create Key-Value list, extracted from parts list PDF document, start from here:
                {pdftxt}

                Key-Value list:";

                //prompt = @$"Summarize the following text concisely and accurately.
                //If the text is too short or doesn't contain meaningful information, state that.

                //Text to summarize:
                //{pdftxt}

                //Summary:";

                // Invoke Ollama text generation service with the prompt.
                var result = await kernel.InvokePromptAsync(prompt); //, cancellationToken: cts.Token);

                // Extract and return the generated summary.
                var summary = result.GetValue<string>()?.Trim() ?? "No summary generated.";
                return summary; // result.GetValue<string>()?.Trim() ?? "No summary generated." 
            }
            return "Kernel is not available.";
        }
        catch (OperationCanceledException)
        {
            if (cts.IsCancellationRequested)
            {
                Console.WriteLine("The operation timed out!");
            }
            return $"The operation timed out.";
        }
        catch (Exception ex)
        {
            Console.WriteLine("Please ensure Ollama is running and the specified model is downloaded.");
            Console.WriteLine($"Error reading file {pdfFileName}: {ex.Message}");
            return $"Error reading file {pdfFileName}: {ex.Message}";
        }

        // https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/GettingStartedWithTextSearch/InMemoryVectorStoreFixture.cs#L139
    }
}

